services:
  rtsapi:
    build:
      context: ./rts-api
    ports:
      - "8000:8000"
    restart: always
  rtsdashboard:
    build:
      context: ./rts-dashboard
    ports:
      - "8050:8050"
    restart: always
